services:
  medclinic-db:
    image: postgres:16-alpine
    container_name: medclinic-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=medclinic_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medclinic-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  medclinic-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medclinic-app-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://medclinic-db:5432/medclinic_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      medclinic-db:
        condition: service_healthy
    networks:
      - medclinic-network

networks:
  medclinic-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
